services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: travel_planner
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=Travel_Planner.settings
